### ISSUE TITLE
 latest Safari browsers, the Show alert messages are called two times.

### ISSUE THREAD

**Issue by dsosarios** [daymosik/react-status-alert#9]
Currently, there is an issue with latest version of Safari browsers (15), the Show alert messages are called two times.

in all other browsers like google chrome, opera, edge, etc are working fine.

for example this message appears two times.

![image](https://user-images.githubusercontent.com/103535333/165860892-3b9d18dd-b2b0-45dd-98e2-da445f110921.png)
![image](https://user-images.githubusercontent.com/103535333/165860947-bd2559f0-17b0-47e9-8608-05709656fa71.png)

**Comment by HiddeRpl** [comment]
Safari got bug with version 15.4. It isn't handling right transitions with multiple properties and different timings. Fix in pull request.

**Comment by daymosik** [comment]
the bug is fixed in Safari 15.5
